# Generated by Django 4.0.1 on 2022-01-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoastProfile',
            fields=[
                ('roast_id', models.UUIDField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('beans', models.TextField(max_length=60)),
                ('weight_in', models.IntegerField()),
                ('weight_out', models.IntegerField()),
                ('batch_num', models.IntegerField()),
                ('batch_of_day', models.IntegerField()),
                ('roasting_notes', models.TextField()),
                ('cupping_notes', models.TextField()),
                ('charge_et', models.FloatField()),
                ('charge_bt', models.FloatField()),
                ('tp_time', models.FloatField()),
                ('tp_et', models.FloatField()),
                ('tp_bt', models.FloatField()),
                ('dry_time', models.FloatField()),
                ('dry_et', models.FloatField()),
                ('dry_bt', models.FloatField()),
                ('drop_time', models.FloatField()),
                ('drop_et', models.FloatField()),
                ('drop_bt', models.FloatField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
